### ISSUE TITLE
Close Add Customer / Add Pet windows after hitting the 'submit' buttons.

### ISSUE THREAD

**Issue by rothlisbergerc** [rothlisbergerc/GroomingSalonRegistrationApp#72]
Upon clicking the submit button (and having passed all validation) on the Add Customer window or Add Pet window, that window should close so that the user is on the main form again. 

**Tasks:**
- [ ] Add Customer Form closes upon passing verification and clicking the submit button.
- [ ] Add Pet Form closes upon passing verification and clicking the submit button.
- [ ] Provide some kind of visual indication that the user entry has been successfully submitted.
